### ISSUE TITLE
Problems about input of docking_py

### ISSUE THREAD

**Issue by OnlyEpisode** [samuelmurail/docking_py#10]
Hello~ I have a problem of input of docking_py. Does the input need to be a binding complex of ligand and receptor? Can the ligand and the receptor be from different files and be of random initial coordinates rather than given positions in the binding complex? 
Thank you for your patience and explanations!

**Comment by samuelmurail** [comment]
Hi,

The example is just a redocking example.
But of course you can use any ligand or receptor structure.
You just need to define in the `Docking` object the `lig_pdb` and `rec_pdb` arguments.

```python
from docking_py import docking

test_dock = docking.Docking('test', lig_pdb='data/lig.pdb', rec_pdb='data/rec.pdb')
test_dock.prepare_ligand()
test_dock.prepare_receptor()
```

Let me know if you encounter more issue.

Cheers

**Comment by OnlyEpisode** [comment]
Thank you~ Besides, I have tried redocking examples in non-GPU and GPU versions respectively, and it seems that the GPU version doesn't accelerate the docking process. Is it normal?

**Comment by samuelmurail** [comment]
In fact it is only the docking which is faster. When you use `run_autodock_docking()` function, it is preparing the grid and then lauch the docking.
But the grid preparation is not accelerated by GPU. 
Anyway in my case the docking itself is clearly accelerated (1080 GTX Ti).

**Comment by OnlyEpisode** [comment]
Oh, so GPU doesn't accelerated the redocking process given in the example?

**Comment by samuelmurail** [comment]
Autodock docking is accelerated with GPU but not the gris preparation.
Have a look here on the github deposit https://github.com/ccsb-scripps/AutoDock-GPU for more details.

Cheers
