### ISSUE TITLE
Problems about Jupyter notebook when installing 0.3.0 version

### ISSUE THREAD

**Issue by OnlyEpisode** [samuelmurail/docking_py#11]
Hello~
When I finish the installation of docking-py 0.3.0 version and try to input "from pdb_manip_py import pdb_manip" in Jupyter notebook under the docking-py virtual enviroment, it shows that " ModuleNotFoundError: No module named 'pdb_manip_py' ". But it is okay when I try the examples in the command line mode.
How to fix it? Thank you very much~

**Comment by samuelmurail** [comment]
From my experience with jupyter notebooks, I would say that jupyter is not using the correct version of python.
Did you install python or ipython in your virtual env ? Are you using conda ?

**Comment by samuelmurail** [comment]
Considered as close as no answer were given.
