### ISSUE TITLE
Configurations about docking tools

### ISSUE THREAD

**Issue by OnlyEpisode** [samuelmurail/docking_py#6]
Hello, may I ask a basic question? Should I install the docking tools (Autodock, Vina, Smina, Qvina2 and Qvinaw) in advance? How  should I configure these tools correctly so that the docking_py programs can find them correctly? Thx~

**Comment by samuelmurail** [comment]
Hi,

Thanks for the interest in docking_py.

The easiest way is to use a conda environment.
Have a look at the doc:
https://docking-py.readthedocs.io/en/latest/installation.html

Cheers
