### ISSUE TITLE
Problems about trying examples in documentation

### ISSUE THREAD

**Issue by OnlyEpisode** [samuelmurail/docking_py#8]
Hello! When I try the examples in "Extract Receptor coordinates with pdb_manip_py" in usage, it appears that “AttributeError: module 'pdb_manip_py.pdb_manip' has no attribute 'PROTEIN_AA'”. How to fix it?

**Comment by samuelmurail** [comment]
Hi,

You are right, the documentation is not up to date, you should use pdb_manip.PROTEIN_RES instead.
I have updated the documentation. Thanks for the report.

Cheers,
Samuel
